[package]
name = "rustng-http"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustng_http"
path = "src/lib.rs"

[dependencies]
rustng-core = { path = "../core" }
rustng-transport = { path = "../transport" }

