[package]
name = "rustng-admin"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustng_admin"
path = "src/lib.rs"

[dependencies]
rustng-core = { path = "../core" }
rustng-config = { path = "../config" }

